## required traits:
#fireRate (seconds, double)
#damage (1/2 hearts, double)
#clipSize (int)
#reloadTime (seconds,double)
#range (blocks,double)
#bulletSize (blocks,double)
##non-required traits:
#particle (Enum from org.bukkit.Particle)

weapons: #list of all weapons (add, delete, or modify as you desire)
  pistol: #name of weapon
    fireRate: 0.5 #seconds until next fire
    damage: 4 #damage on hit (in half hearts)
    clipSize: 8 #shots until reload required MUST BE INT
    reloadTime: 2 #seconds to reload
    range: 20 #range in blocks (render/simulation distance may apply)
    particle: "ASH" #particle to be used on impact, optional, will not display particle if not present
    bulletSize: 0.2 #size of the ray for the raycast
  sniper:
    fireRate: 1
    damage: 30
    clipSize: 4
    reloadTime: 3
    range: 20
    bulletSize: 0.1
WeaponStop: yes #used in the code to tell when the weapon configurations stop DO NOT DELETE